# Generated by Django 2.0.7 on 2018-07-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grupo',
            field=models.ForeignKey(help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='grupo'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ocupacion',
            field=models.ForeignKey(help_text='', null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Ocupacion', verbose_name='grupo'),
        ),
    ]
